general {
    hide_cursor = true
    ignore_empty_input = true
}

auth {
    fingerprint {
        enabled = true
        retry_delay = 500
    }
}

background {
    monitor = desc:AU Optronics 0x233D
    path = ~/wallpapers/main.png
    blur_passes = 3
}

input_field {
    monitor = desc:AU Optronics 0x233D
    hide_input = true
}
